DROP TABLE IF EXISTS EMPLOYEE;
 
CREATE TABLE EMPLOYEE (
  EMPLOYEE_ID INT AUTO_INCREMENT  PRIMARY KEY,
  FIRST_NAME VARCHAR(250) NOT NULL,
  LAST_NAME VARCHAR(250) NOT NULL,
  DATE_OF_BIRTH DATE NOT NULL,
  ADDRESS_ID VARCHAR(250) NOT NULL,
  FOREIGN KEY (ADDRESS_ID) REFERENCES ADDRESS(ADDRESS_ID)
);

DROP TABLE IF EXISTS ADDRESS;

CREATE TABLE ADDRESS (
  ADDRESS_ID INT AUTO_INCREMENT  PRIMARY KEY,
  LINE1 VARCHAR(250) NOT NULL,
  LINE2 VARCHAR(250),
  CITY VARCHAR(250) NOT NULL,
  STATE VARCHAR(250) NOT NULL,
  COUNTRY VARCHAR(250) NOT NULL,
  ZIP_CODE VARCHAR(250) NOT NULL
);